services:
  - type: web
    name: deep-cord
    runtime: docker
    repo: https://github.com/JakubStiburek/deep-cord
    plan: free
    envVars:
      - key: PORT
        sync: false
      - key: PG_PASSWORD
        sync: false
      - key: PG_USER
        sync: false
      - key: PG_DATABASE
        sync: false
      - key: PG_HOST
        sync: false
      - key: UPLOAD_DIRECTORY_PATH
        sync: false
      - key: NODE_ENV
        sync: false
    region: frankfurt
    dockerContext: .
    dockerfilePath: ./Dockerfile
    rootDir: api

  - type: web
    name: deep-cord-web
    runtime: static
    repo: https://github.com/JakubStiburek/deep-cord
    envVars:
      - key: VITE_API_URL
        sync: false
    buildCommand: pnpm install --frozen-lockfile; pnpm run build
    staticPublishPath: dist
    rootDir: frontend

  - type: web
    name: woodpecker-server
    plan: free
    runtime: docker
    image:
      url: woodpeckerci/woodpecker-server:latest
    envVars:
      - key: PORT
        value: "8000"
      - key: WOODPECKER_OPEN
        value: "true"
      - key: WOODPECKER_HOST
        value: "your-woodpecker-host"
      - key: WOODPECKER_GITHUB
        value: "true"
      - key: WOODPECKER_GITHUB_CLIENT
        sync: false
      - key: WOODPECKER_GITHUB_SECRET
        sync: false
      - key: WOODPECKER_AGENT_SECRET
        sync: false
    region: frankfurt
    disk:
      mountPath: /var/lib/woodpecker
      name: woodpecker-server-data
      sizeGB: 1

  - type: worker
    name: woodpecker-agent
    plan: free
    runtime: docker
    image:
      url: woodpeckerci/woodpecker-agent:latest
    envVars:
      - key: WOODPECKER_SERVER
        value: "http://woodpecker-server:9000"
      - key: WOODPECKER_AGENT_SECRET
        sync: false
    startCommand: "agent"
    region: frankfurt

version: "1"
