services:
  - type: web
    name: deep-cord
    runtime: docker
    repo: https://github.com/JakubStiburek/deep-cord
    plan: free
    envVars:
      - key: PORT
        sync: false
      - key: PG_PASSWORD
        sync: false
      - key: PG_USER
        sync: false
      - key: PG_DATABASE
        sync: false
      - key: PG_HOST
        sync: false
      - key: UPLOAD_DIRECTORY_PATH
        sync: false
      - key: NODE_ENV
        sync: false
    region: frankfurt
    dockerContext: .
    dockerfilePath: ./Dockerfile
    rootDir: api

  - type: web
    name: deep-cord-web
    runtime: static
    repo: https://github.com/JakubStiburek/deep-cord
    envVars:
      - key: VITE_API_URL
        sync: false
    buildCommand: pnpm install --frozen-lockfile; pnpm run build
    staticPublishPath: dist
    rootDir: frontend

version: "1"
