/* tslint:disable */
/* eslint-disable */

/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgresql://username:password@localhost:5432/deep_cord -t annotation -t file -t schema_migrations -s public
 *
 */

export type Json = unknown;

// Table annotation
export interface Annotation {
  id: string;
  start_time: number;
  end_time: number;
  type: string;
  value: string;
  created_at: Date;
  file_id: string;
}
export interface AnnotationInput {
  id?: string;
  start_time: number;
  end_time: number;
  type: string;
  value: string;
  created_at?: Date;
  file_id: string;
}
const annotation = {
  tableName: 'annotation',
  columns: [
    'id',
    'start_time',
    'end_time',
    'type',
    'value',
    'created_at',
    'file_id',
  ],
  requiredForInsert: ['start_time', 'end_time', 'type', 'value', 'file_id'],
  primaryKey: 'id',
  foreignKeys: {
    file_id: { table: 'file', column: 'id', $type: null as unknown as File },
  },
  $type: null as unknown as Annotation,
  $input: null as unknown as AnnotationInput,
} as const;

// Table file
export interface File {
  id: string;
  uri: string;
  name: string;
  created_at: Date;
}
export interface FileInput {
  id?: string;
  uri: string;
  name: string;
  created_at?: Date;
}
const file = {
  tableName: 'file',
  columns: ['id', 'uri', 'name', 'created_at'],
  requiredForInsert: ['uri', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as File,
  $input: null as unknown as FileInput,
} as const;

// Table schema_migrations
export interface SchemaMigrations {
  version: number;
  dirty: boolean;
}
export interface SchemaMigrationsInput {
  version: number;
  dirty: boolean;
}
const schema_migrations = {
  tableName: 'schema_migrations',
  columns: ['version', 'dirty'],
  requiredForInsert: ['version', 'dirty'],
  primaryKey: 'version',
  foreignKeys: {},
  $type: null as unknown as SchemaMigrations,
  $input: null as unknown as SchemaMigrationsInput,
} as const;

export interface TableTypes {
  annotation: {
    select: Annotation;
    input: AnnotationInput;
  };
  file: {
    select: File;
    input: FileInput;
  };
  schema_migrations: {
    select: SchemaMigrations;
    input: SchemaMigrationsInput;
  };
}

export const tables = {
  annotation,
  file,
  schema_migrations,
};
