/* tslint:disable */
/* eslint-disable */


/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgresql://username:password@localhost:5432/deep_cord -t file -t schema_migrations -s public
 *
 */


export type Json = unknown;

// Table file
export interface File {
  id: string;
  uri: string;
  name: string;
  created_at: Date;
}
export interface FileInput {
  id?: string;
  uri: string;
  name: string;
  created_at?: Date;
}
const file = {
  tableName: 'file',
  columns: ['id', 'uri', 'name', 'created_at'],
  requiredForInsert: ['uri', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as File,
  $input: null as unknown as FileInput
} as const;

// Table schema_migrations
export interface SchemaMigrations {
  version: number;
  dirty: boolean;
}
export interface SchemaMigrationsInput {
  version: number;
  dirty: boolean;
}
const schema_migrations = {
  tableName: 'schema_migrations',
  columns: ['version', 'dirty'],
  requiredForInsert: ['version', 'dirty'],
  primaryKey: 'version',
  foreignKeys: {},
  $type: null as unknown as SchemaMigrations,
  $input: null as unknown as SchemaMigrationsInput
} as const;


export interface TableTypes {
  file: {
    select: File;
    input: FileInput;
  };
  schema_migrations: {
    select: SchemaMigrations;
    input: SchemaMigrationsInput;
  };
}

export const tables = {
  file,
  schema_migrations,
}
