/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/audio/files": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description List files in storage. */
    get: operations["FilesController_listUploadedFiles"];
    put?: never;
    /** @description Upload audio files to storage. */
    post: operations["FilesController_uploadAudioFile"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/audio/files/{id}/transcriptions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Request transcription of a file */
    post: operations["FilesController_transcribeFile"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/records/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get a record by it's id. */
    get: operations["RecordController_getRecord"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/records/{id}/annotations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Add annotation to record */
    post: operations["RecordController_addAnnotation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["HealthController_check"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    UploadFileDto: {
      /** @example my-audio-file */
      name?: string;
      /**
       * @description Extension is inferred from filename, this field overrides it. If none is provided file extension defaults to mp3.
       * @example mp3
       */
      extension?: string;
      /** Format: binary */
      file: string;
    };
    FileDto: {
      /** @example 4b61aa1d-4c42-4e60-b8f5-04735e8b6999 */
      id: string;
      /** @example my-audio-file.mp3 */
      name: string;
      /** @example ./uploads/record-original-file-name-2024-12-24.mp4 */
      uri: string;
      /** @example 2025-01-12T18:17:33.654+01:00 */
      createdAt: string;
      transcribed: boolean;
    };
    ListUploadedFilesResponseDto: {
      /** @description List of uploaded files. */
      files: components["schemas"]["FileDto"];
    };
    AnnotationSpanDto: {
      /** @example 15.55 */
      start: number;
      /** @example 16.75 */
      end: number;
    };
    AnnotationDto: {
      /** @example 1696f02e-d3a8-4084-bc32-b76738afefeb */
      id: string;
      /** @description Seconds */
      span: components["schemas"]["AnnotationSpanDto"];
      /**
       * @example transcript
       * @enum {string}
       */
      type: "transcript" | "confidence" | "speaker";
      /** @example word */
      value: Record<string, never>;
    };
    AnnotationTierDto: {
      annotations: components["schemas"]["AnnotationDto"][];
      type: string;
    };
    GetRecordResponseDto: {
      /** @example 1696f02e-d3a8-4084-bc32-b76738afefeb */
      id: string;
      file: components["schemas"]["FileDto"];
      annotationTiers: components["schemas"]["AnnotationTierDto"][];
    };
    CreateAnnotationDto: {
      /** @description Seconds */
      span: components["schemas"]["AnnotationSpanDto"];
      /**
       * @example transcript
       * @enum {string}
       */
      type: "transcript" | "confidence" | "speaker";
      /** @example word */
      value: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  FilesController_listUploadedFiles: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListUploadedFilesResponseDto"];
        };
      };
    };
  };
  FilesController_uploadAudioFile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["UploadFileDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FileDto"];
        };
      };
    };
  };
  FilesController_transcribeFile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  RecordController_getRecord: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetRecordResponseDto"];
        };
      };
    };
  };
  RecordController_addAnnotation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateAnnotationDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthController_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Health Check is successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example ok */
            status?: string;
            /** @example {
             *       "database": {
             *         "status": "up"
             *       }
             *     } */
            info?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /** @example {} */
            error?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /** @example {
             *       "database": {
             *         "status": "up"
             *       }
             *     } */
            details?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
      /** @description The Health Check is not successful */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example error */
            status?: string;
            /** @example {
             *       "database": {
             *         "status": "up"
             *       }
             *     } */
            info?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /** @example {
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect"
             *       }
             *     } */
            error?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /** @example {
             *       "database": {
             *         "status": "up"
             *       },
             *       "redis": {
             *         "status": "down",
             *         "message": "Could not connect"
             *       }
             *     } */
            details?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            };
          };
        };
      };
    };
  };
}
