name: CI

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
  pull_request:
    branches:
      - main
    paths:
      - "api/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: ./api
        run: pnpm install

      - name: Build application
        working-directory: ./api
        run: pnpm run build

      - name: Run tests
        working-directory: ./api
        run: pnpm test

  # setup:
  #   name: Setup Neon
  #   outputs:
  #     branch: ${{ steps.branch_name.outputs.current_branch }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get branch name
  #       id: branch_name
  #       uses: tj-actions/branch-names@v8
  #
  # create_neon_branch:
  #   name: Integration Tests
  #   outputs:
  #     db_url: ${{ steps.create_neon_branch_encode.outputs.db_url }}
  #     db_url_with_pooler: ${{ steps.create_neon_branch_encode.outputs.db_url_with_pooler }}
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Create Neon Branch
  #       id: create_neon_branch
  #       uses: neondatabase/create-branch-action@v5
  #       with:
  #         project_id: ${{ vars.NEON_PROJECT_ID }}
  #         branch_name: preview/${{ github.sha }}
  #         parent: main
  #         database: deep_cord
  #         api_key: ${{ secrets.NEON_API_KEY }}
  #
  #     - name: Extract endpoint
  #       id: extract_endpoint
  #       run: |
  #         ENDPOINT=$(echo "${{ steps.create_neon_branch.outputs.db_url }}" | grep -o 'ep-[^.]*')
  #         echo "endpoint=$ENDPOINT" >> $GITHUB_OUTPUT
  #
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #
  #     - name: Install PNPM
  #       run: npm install -g pnpm
  #
  #     - name: Install golang-migrate
  #       run: |
  #         curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.0/migrate.linux-amd64.tar.gz | tar xz
  #         sudo mv migrate /usr/local/bin/migrate
  #         migrate -version
  #
  #     - name: Install dependencies
  #       working-directory: ./api
  #       run: pnpm install
  #
  #     - name: Run Database Migration
  #       working-directory: ./api
  #       env:
  #         NEON_CONNECTION_URL: "${{ steps.create_neon_branch.outputs.db_url }}&options=endpoint%3D${{ steps.extract_endpoint.outputs.endpoint }}"
  #       run: pnpm run db:prod:migrate
  #
  #     - name: Run Integration Tests
  #       working-directory: ./api
  #       run: pnpm run test:integration
  #
  # delete_neon_branch:
  #   name: Delete Neon Branch
  #   needs: create_neon_branch
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Delete Neon Branch
  #       uses: neondatabase/delete-branch-action@v3
  #       with:
  #         project_id: ${{ vars.NEON_PROJECT_ID }}
  #         branch: preview/${{ github.sha }}
  #         api_key: ${{ secrets.NEON_API_KEY }}
